<?php
/**
 * This template displays the single Product
 *
 * @package genesis_connect_woocommerce
 * @version 0.9.8
 *
 * Note for customisers/users: Do not edit this file!
 * ==================================================
 * If you want to customise this template, copy this file (keep same name) and place the
 * copy in the child theme's woocommerce folder, ie themes/my-child-theme/woocommerce
 * (Your theme may not have a 'woocommerce' folder, in which case create one.)
 * The version in the child theme's woocommerce folder will override this template, and
 * any future updates to this plugin won't wipe out your customisations.
 *
 */

/** Remove default Genesis loop */
remove_action( 'genesis_loop', 'genesis_do_loop' );

/** Remove WooCommerce breadcrumbs */
remove_action( 'woocommerce_before_main_content', 'woocommerce_breadcrumb', 20 );

/** Uncomment the below line of code to add back WooCommerce breadcrumbs */
//add_action( 'genesis_before_loop', 'woocommerce_breadcrumb', 10, 0 );

/** Remove Woo #container and #content divs */
remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10 );
remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10 );


add_action( 'genesis_loop', 'gencwooc_single_product_loop' );
/**
 * Displays single product loop
 *
 * Uses WooCommerce structure and contains all existing WooCommerce hooks
 *
 * Code based on WooCommerce 1.5.5 woocommerce_single_product_content()
 * @see woocommerce/woocommerce-template.php
 *
 * @since 0.9.0
 */
function gencwooc_single_product_loop() {

    do_action( 'woocommerce_before_main_content' );

        $productTerms = get_the_terms( $post->ID, 'product_cat' );

        $args = array(
            'post_type' => 'product',
            'product_cat' => $productTerms[0]->slug,
            'orderby' => 'rand'
        );
        $loop = new WP_Query( $args ); ?>
        <div class="container">
            <h3 class="text-center">Elige tu modelo</h3>
            <nav class="row justify-content-md-center border-t border-b">
                <div class="wrap">
                    <ul class="menu genesis-nav-menu">
                    <?php while ( $loop->have_posts() ) : $loop->the_post(); global $product; ?>
                        <li class="menu-item menu-item-type-custom menu-item-object-custom">
                            <a class="col" href="<?php the_permalink(); ?>" itemprop="url">
                                <span itemprop="name"><?php the_title(); ?></span>
                            </a>
                        </li>
                    <?php endwhile; ?>
                    </ul>
                </div>
            </nav>
        </div>
        <?php wp_reset_query();

	// Let developers override the query used, in case they want to use this function for their own loop/wp_query
	$wc_query = false;

	// Added a hook for developers in case they need to modify the query
	$wc_query = apply_filters( 'gencwooc_custom_query', $wc_query );

	if ( ! $wc_query) {

		global $wp_query;

		$wc_query = $wp_query;
	}

	if ( $wc_query->have_posts() ) while ( $wc_query->have_posts() ) : $wc_query->the_post(); ?>

		<?php do_action('woocommerce_before_single_product'); ?>

		<div id="product-<?php the_ID(); ?>" <?php post_class('row'); ?>>

            <div id="configurator" class="col-sm-3">
                <div class="js-choice">
                    <h3 class="title-bg-black text-center">1.-Personaliza tu plantilla</h3>
                    <div class="select-zone row">
                        <?php
                        global $product;
                        $attributes = $product->get_attributes();
                        foreach ( $attributes as $attribute ):
                            $attribute_name  = $attribute->get_taxonomy(); // The taxonomy slug name
                            $attribute_icon  = get_field('icon_'.$attribute_name);
                            $attribute_label = strip_tags(wc_attribute_label($attribute_name));
                            echo '<span class="col-6 col-sm-6 col-lg-3 seccion_imagen" id="' . $attribute_name . '"><img data-toggle="tooltip" data-placement="bottom" data-html="true" title="<h4>'.$attribute_label.'</h4>" src="' . $attribute_icon . '"></span>';
                        endforeach;
                        ?>
                        <h4>Aplica un color y/o material</h4>
                        <?php echo woocommerce_template_single_add_to_cart(); ?>
                    </div>
                </div>
            </div>

            <div id="product-image" class="col-sm-6">
                <?php
                    /**
                     * Hook: woocommerce_before_single_product_summary.
                     *
                     * @hooked woocommerce_show_product_sale_flash - 10
                     * @hooked woocommerce_show_product_images - 20
                     */
                    do_action( 'woocommerce_before_single_product_summary' );
                ?>
            </div>

            <div id="summary" class="col-sm-3">
                <div class="entry-summary text-center">
                    <?php
                        /**
                         * Hook: woocommerce_single_product_summary.
                         *
                         * @hooked woocommerce_template_single_title - 5
                         * @hooked woocommerce_template_single_rating - 10
                         * @hooked woocommerce_template_single_price - 10
                         * @hooked woocommerce_template_single_excerpt - 20
                         * @hooked woocommerce_template_single_add_to_cart - 30
                         * @hooked woocommerce_template_single_meta - 40
                         * @hooked woocommerce_template_single_sharing - 50
                         * @hooked WC_Structured_Data::generate_product_data() - 60
                         */
                        //do_action( 'woocommerce_single_product_summary' );

                        ?>
                        <div class="js-choice">
                            <h3 class="title-bg-black">Tu modelo</h3>
                            <?php echo woocommerce_template_single_title(); ?>
                            <div class="js-list-parts row text-left">
                                <?php
                                    global $product;
                                    $attributes = $product->get_attributes();
                                    foreach ( $attributes as $attribute ):
                                        $attribute_name = $attribute->get_taxonomy(); // The taxonomy slug name
                                        $attribute_icon = get_field('icon_'.$attribute_name);

                                        echo '<div class="col-12"><img src="' . $attribute_icon . '"> <span id="js-selected-' . $attribute_name . '"></span></div><br>';
                                    endforeach;
                                ?>
                                <div class="clear"></div>
                                <div id="js-stamped-text-selected-container" class="col-12 d-none">
                                    <br>
                                    <h3>Tu texto para el interior</h3>
                                    <p id="js-stamped-text-selected" style="border: dashed 1px; padding: 5px;"></p>
                                    <div id="js-stamped-text-notice" class="alert alert-info text-center" role="alert">
                                        <p>Este bordado tiene un sobrecoste de <?php echo get_field( 'fee_stamp' ); ?> €.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="separator">
                            <p>PVP</p>
                            <p>+ gastos de envío</p>
                        </div>
                        <?php echo woocommerce_template_single_price(); ?>
                        <div id="js-ad-to-cart">

                        </div>
                </div>
            </div>

            <div class="col-12">
                <?php
                    /**
                     * Hook: woocommerce_after_single_product_summary.
                     *
                     * @hooked woocommerce_output_product_data_tabs - 10
                     * @hooked woocommerce_upsell_display - 15
                     * @hooked woocommerce_output_related_products - 20
                     */
                    do_action( 'woocommerce_after_single_product_summary' );
                ?>
            </div>

		</div>

		<?php do_action( 'woocommerce_after_single_product' );

	endwhile;

	do_action( 'woocommerce_after_main_content' );
} ?>
<style>
.single_variation_wrap .price {
    display: none;
}
</style>
<?php
genesis();